language: scala
jdk: oraclejdk8
scala:
   - 2.12.8
addons:
  sonarcloud:
    organization: "justin-yan-github"
script:
  - sbt clean coverage test coverageReport
  - sonar-scanner
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    - justin.yan.public@gmail.com
